### ISSUE TITLE
[Buttons]: When you click on the button on mobile, the text is marked

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#540] opened 2022-07-14 12:31 UTC
### Description

![IMG_F45975527D4A-1](https://user-images.githubusercontent.com/10883919/178982255-54a9d65f-dde0-4309-bdb9-2b16a8e47455.jpeg)

### Component(s) impacted

button

### Vivid Web Components version

vivid-next

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

vivid

### CodeSandbox example

.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by yinonov** [comment] 2022-07-14 13:53
it can be easily resolved with `user-select: none`.
do other libs set that style on actions?

**Comment by rinaok** [comment] 2022-07-14 14:02
@yinonov Fast also has that bug

**Comment by yinonov** [comment] 2022-07-14 16:16
It's a style issue which isn't scoped to foundation class. I figure this is a choice to make and i'm not aware of any issues preventing user select but there could be...
It's not a bug as is an expected behaviour in native button as well. Isn't it?

**Comment by rinaok** [comment] 2022-07-14 16:20
@yinonov It is expected that desktop buttons will behave the same way as mobile buttons.

**Comment by yinonov** [comment] 2022-07-14 19:35
Does it happen on iOS? I'll check

**Closed** 2022-07-19 07:05 UTC
Labels: Type: Bug :lady_beetle:
