### ISSUE TITLE
Migrate design tokens to vivid-3

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#219] opened 2022-02-23 09:22 UTC
- [ ] Move the css tokens generator to https://github.com/Vonage/vivid-design-tokens-properties and publish the css results too
- [ ] Move https://github.com/Vonage/vivid-design-tokens-properties to vivid as a publishable library and build its CI/CD process in vivid
- [ ] Use executors for the new lib in order to fetch and build the tokens

**Comment by yinonov** [comment] 2022-02-24 14:57
duplicate of #218?

**Closed** 2022-08-07 11:35 UTC
Labels: Type: Refactor :recycle:
